name: Enterlab
favicon: null
layout_spectrum: 0.41156
typography_spectrum: 0.46883
title: Enterlab - Enterprise IT Laboratory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f6'
    - '#00aeef'
    - '#000000'
    - '#004c68'
    - '#8a8b8c'
  brandStrength: 0.625
  lightness: 0.8781285609584302
  saturation: 0.1862778104841709
  rhythmicContrast: 0.8476225363556296
purpose: []
